apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.nodeservice.port }}
      targetPort: {{ .Values.nodeservice.targetPort }}
  type: {{ .Values.nodeservice.type }}
